### ISSUE TITLE
error thrown when result is null for starknet_getBlock

### ISSUE THREAD

**Issue by moodysalem** [0xs34n/starknet.js#682] opened 2023-07-10 23:25 UTC
https://github.com/0xs34n/starknet.js/blob/7bc96fae09c4cfb0427b622794be884d3dc4e554/src/provider/rpc.ts#L106

infura rpc returns null for getBlock when it's not known, then the rpc crashes because it can't destructure null

**Comment by tabaktoni** [comment] 2023-07-12 08:55
Hi @moodysalem, Thank you for reporting, and please use provided template for Bugs, so we can reduce back and forth with questions.
Closing due to insufficient information provided to reproduce.

Note:
This is probably related to their node update which returned null on all endpoints yesterday.

If this issue is not resolved, please reopen it using the bug template and provide minimal code to reproduce it.

**Closed by tabaktoni** 2023-07-12 08:55 UTC
